export const NICHE_CONFIGS = {
  senior_scam_prevention: {
    niche_name_ja: '高齢者向け詐欺対策',
    niche_name_vi: 'Chống lừa đảo cho người già',
    audience: 'Japanese seniors and their families',
    emotional_tone: 'serious, protective, urgent but not panic',
    core_topics: ['特殊詐欺', '電話詐欺', '還付金詐欺', '銀行口座', '家族への相談', '警察・自治体への確認'],
    visual_keywords: [
      'elderly Japanese person receiving suspicious phone call',
      'warning mark',
      'bank card',
      'fraud prevention checklist',
      'family support',
    ],
    thumbnail_angles: ['知らないと危険', 'その電話、危ない', '高齢者が狙われる理由', '家族が守るべきサイン'],
    avoid_claims: ['exact crime statistics unless provided', 'specific legal advice', 'guaranteed prevention'],
    title_style: 'warning + practical benefit',
    scene_density: 'medium-high',
  },

  senior_smartphone_safety: {
    niche_name_ja: 'シニア向けスマホ安全',
    niche_name_vi: 'Smartphone an toàn cho senior',
    audience: 'Japanese seniors using smartphones',
    emotional_tone: 'friendly, reassuring, practical',
    core_topics: ['迷惑メール', 'LINE詐欺', 'パスワード', 'スマホ設定', '怪しいリンク', '二段階認証'],
    visual_keywords: [
      'elderly Japanese person using smartphone',
      'large smartphone screen',
      'security lock icon',
      'simple settings guide',
      'family member helping',
    ],
    thumbnail_angles: ['その設定、大丈夫？', '押してはいけないリンク', 'スマホ詐欺を防ぐ', '今すぐ確認したい設定'],
    avoid_claims: ['specific app UI if not described', 'brand logos', 'guaranteed safety'],
    title_style: 'problem + easy solution',
    scene_density: 'high',
  },

  senior_pension_easy: {
    niche_name_ja: '年金をやさしく解説',
    niche_name_vi: 'Giải thích lương hưu dễ hiểu',
    audience: 'Japanese seniors approaching retirement',
    emotional_tone: 'calm, educational, trustworthy',
    core_topics: ['年金', '老齢年金', '繰上げ受給', '繰下げ受給', '受給開始年齢', '手続き', '注意点'],
    visual_keywords: [
      'elderly Japanese couple',
      'pension documents',
      'calendar',
      'yen symbols',
      'simple comparison chart',
      'government-style explanation board',
    ],
    thumbnail_angles: ['年金の落とし穴', '知らないと損する', '60歳・65歳の違い', '受け取り方で差が出る'],
    avoid_claims: ['invented monetary amounts', 'unverified law changes', 'personal financial advice'],
    title_style: 'benefit + caution + easy explanation',
    scene_density: 'medium',
  },

  pension_life_saving: {
    niche_name_ja: '年金生活の節約術',
    niche_name_vi: 'Tiết kiệm khi sống bằng lương hưu',
    audience: 'Japanese seniors living on pension',
    emotional_tone: 'practical, empathetic, hopeful',
    core_topics: ['節約', '固定費', '食費', '電気代', '医療費', '生活費', '家計管理'],
    visual_keywords: [
      'elderly Japanese woman checking household budget',
      'grocery receipt',
      'monthly expense chart',
      'yen coins',
      'simple savings checklist',
    ],
    thumbnail_angles: ['年金生活で差が出る', '毎月のムダを減らす', '知らない節約術', '老後のお金を守る'],
    avoid_claims: ['guaranteed savings amount', 'extreme poverty depiction', 'shaming seniors'],
    title_style: 'practical saving + emotional relief',
    scene_density: 'high',
  },

  end_of_life_planning: {
    niche_name_ja: '終活の始め方',
    niche_name_vi: 'Chuẩn bị cuối đời nhập môn',
    audience: 'Japanese seniors and adult children',
    emotional_tone: 'gentle, respectful, calm',
    core_topics: ['終活', 'エンディングノート', '葬儀', '財産整理', '家族への伝言', '医療・介護の希望'],
    visual_keywords: [
      'elderly Japanese person writing notebook',
      'family discussion',
      'documents on table',
      'warm living room',
      'gentle checklist',
    ],
    thumbnail_angles: ['終活は何から始める？', '家族に迷惑をかけない準備', '最初に書くべきこと', '後悔しない終活'],
    avoid_claims: ['fear-based death imagery', 'legal certainty without source', 'dark funeral visuals'],
    title_style: 'gentle beginner guide',
    scene_density: 'medium',
  },

  inheritance_will_intro: {
    niche_name_ja: '相続・遺言の超入門',
    niche_name_vi: 'Thừa kế / di chúc cực dễ hiểu',
    audience: 'Japanese seniors and families',
    emotional_tone: 'serious, clear, preventive',
    core_topics: ['相続', '遺言', '財産分割', '家族トラブル', '手続き', '専門家相談'],
    visual_keywords: [
      'elderly Japanese couple reviewing documents',
      'family meeting',
      'inheritance document',
      'seal stamp',
      'simple family tree diagram',
    ],
    thumbnail_angles: ['相続で揉めないために', '遺言の基本', '知らないと家族が困る', '最初に確認すべきこと'],
    avoid_claims: ['specific legal advice', 'fake legal results', 'invented inheritance amounts'],
    title_style: 'risk prevention + beginner explanation',
    scene_density: 'medium',
  },
};
