/**
 * CSS selector Playwright cho luồng upload YouTube Studio (GPM).
 */
export const YOUTUBE_SELECTOR = {
  btnCreate: '#buttons ytd-button-renderer button',
  btnUploadVideo: '#items ytd-compact-link-renderer:nth-of-type(1) a',
  btnSelectFile: '#select-files-button button',
  formDetails: 'ytcp-uploads-dialog:not([workflow-step="SELECT_FILES"])',
  titleBox: '#title-wrapper #textbox',
  descriptionBox: '#description-wrapper #textbox',
  thumbnailBox: '#custom-still-editor-wrapper #select-button',
  boxUpload: '#scrollable-content',
  btnShowMore: '#toggle-button button',
  tagsBox: '#tags-container',
  tagsInput: '#tags-container input',
  btnNextToRelatedStep: '#next-button button',
  btnAddVideoRelated: '#endscreens-button button',
  btnChooseTemplate: '#cards-row > div:nth-of-type(1) .template-preview',
  btnSelectElement: '#add-element-menu-button button',
  btnSelectVideo: '#paper-list #text-item-0',
  btnSaveRelatedVideo: '#save-button button',
  btnNextToCheckStep: '#next-button button',
  btnNextToVisibilityStep: '#next-button button',
  btnChooseSchedule: '#visibility-container #second-container',
  btnSelectDate: '#datepicker-trigger div',
  inputDate: 'ytcp-date-picker #labelAndInputContainer input',
  inputTime: '.ytcp-datetime-picker input',
  startTime: 'ytve-framestamp-input#start-input',
  endTime: 'ytve-framestamp-input#end-input',
  btnSaveSchedule: '#done-button button',
  popupScheduleSuccess: '#dialog ytcp-video-thumbnail-with-info',
  popupProcessing: 'ytcp-uploads-still-processing-dialog #dialog',
  popupWarning: 'ytcp-prechecks-warning-dialog #dialog',
  btnGotItWarning: 'ytcp-prechecks-warning-dialog #primary-action-button button',
};
