export const promptToCreateBottomTextThumbnailSpec = ({ title, summary, visualStyle, visualPromptConstant }) => `
You are a top-performing Japanese YouTube thumbnail strategist, copywriter, color director, and visual prompt engineer.

Your task is to analyze a Japanese video title and summary, then create a production-ready JSON spec for an automated thumbnail renderer.

The final thumbnail will be rendered by code.

INPUT:
Title:
${title}

Summary:
${summary}

Requested visual style:
${visualStyle}

━━━━━━━━━━━━━━━━━━━━
VISUAL PROMPT CONSTANTS PROVIDED BY CODE
━━━━━━━━━━━━━━━━━━━━

You must use the following visual prompt constants as the base rules for creating "visual_prompt".

Positive style rules:
${visualPromptConstant?.positivePrefix || ''}

Negative style rules:
${visualPromptConstant?.negativeRules || ''}

Safe area rules:
${visualPromptConstant?.safeAreaRules || ''}

Important:
- The final "visual_prompt" must follow these constants.
- Do not contradict these constants.
- Add story-specific characters, setting, emotion, objects, and composition based on the title and summary.
- The final "visual_prompt" must be written in English only.
- The final "visual_prompt" must not include the Japanese thumbnail copy.

━━━━━━━━━━━━━━━━━━━━
FINAL THUMBNAIL FORMAT
━━━━━━━━━━━━━━━━━━━━

- Canvas: 1280x720
- Japanese drama thumbnail
- Visual background generated by AI
- Final Japanese text rendered later by code
- Bottom text must have exactly 2 lines
- Optional top quote may be used only when it improves CTR
- Font size will be handled by code
- Do not decide exact font size
- You must choose text colors based on the detected niche
- You must provide fill color and stroke color for each text line
- Stroke color should usually be black or near-black for readability
- The image-generation prompt must create the visual background only
- The image-generation prompt must NOT ask the model to render Japanese text

━━━━━━━━━━━━━━━━━━━━
LANGUAGE RULE
━━━━━━━━━━━━━━━━━━━━

- Values inside "thumbnail_copy" must be Japanese.
- All other fields must be English.
- Do not write Japanese outside "thumbnail_copy".
- The visual prompt must be written in English only.
- The image-generation prompt must not include the Japanese thumbnail text.

━━━━━━━━━━━━━━━━━━━━
COPY RULES
━━━━━━━━━━━━━━━━━━━━

Create exactly:

1. bottom_line_1
2. bottom_line_2
3. optional top_quote

bottom_line_1:
- Role: context setup
- Should explain the situation quickly
- Usually includes the conflict, relationship, or trigger
- Recommended length: 18–32 Japanese full-width characters
- Must be readable on mobile

bottom_line_2:
- Role: strongest punchline, twist, revenge, reveal, or emotional hook
- Must be more clickable than bottom_line_1
- Recommended length: 14–30 Japanese full-width characters
- Can use a short quote when powerful
- Should create curiosity or emotional satisfaction

top_quote:
- Optional
- Use only when there is a strong short dialogue, call, confession, or shocking phrase
- Recommended length: 6–16 Japanese full-width characters
- If not useful, set top_quote_enabled to false and top_quote to an empty string

Japanese punctuation rules:
- Allowed: 「」 … ... ！？ ! ?
- Avoid overusing punctuation
- Do not use these characters: 【】『』《》[]()、。
- Do not use emojis
- Do not use hashtags
- Do not use line breaks inside each text value

━━━━━━━━━━━━━━━━━━━━
CTR COPY PATTERNS
━━━━━━━━━━━━━━━━━━━━

Use the most suitable pattern based on the story:

1. Revenge after divorce:
Setup: "After divorce, the person who looked down on me came back"
Punchline: "I coldly replied / rejected / exposed them"

2. Affair or DNA betrayal:
Setup: "The spouse brought an affair partner / pregnancy / suspicious evidence"
Punchline: "The DNA test / evidence destroyed everything"

3. Mother-in-law conflict:
Setup: "The ex-mother-in-law called / begged / mocked"
Punchline: "The protagonist answered coldly or revealed the reversal"

4. Success reversal:
Setup: "The abandoned protagonist became successful"
Punchline: "The former family panicked, begged, or regretted it"

5. Hidden secret:
Setup: "A suspicious object, message, SNS, or disappearance appears"
Punchline: "The hidden truth is revealed"

6. Legal collapse:
Setup: "Divorce, lawyer, police, compensation, debt, or trial begins"
Punchline: "The antagonist loses everything"

━━━━━━━━━━━━━━━━━━━━
COLOR SELECTION RULES
━━━━━━━━━━━━━━━━━━━━

You must choose one color theme based on the detected niche.

Available color themes:

1. cyan_white_revenge
Use for:
- divorce revenge
- mother-in-law revenge
- ex-husband/ex-wife comeback
- cold rejection
- social reversal
Colors:
- bottom_line_1 fill: #FFFFFF
- bottom_line_2 fill: #14F7FF
- top_quote fill: #48FF4E
- stroke: #111111

2. yellow_red_betrayal
Use for:
- affair
- cheating
- DNA test
- pregnancy deception
- betrayal
- hidden lover
Colors:
- bottom_line_1 fill: #FFF200
- bottom_line_2 fill: #FF2A2A
- top_quote fill: #FFFFFF
- stroke: #111111

3. gold_white_success
Use for:
- success after being abandoned
- money
- TV appearance
- luxury life
- status reversal
- business success
Colors:
- bottom_line_1 fill: #FFFFFF
- bottom_line_2 fill: #FFD700
- top_quote fill: #48FF4E
- stroke: #111111

4. blue_white_emotional
Use for:
- family emotion
- regret
- tears
- reunion
- parent-child drama
- healing or redemption
Colors:
- bottom_line_1 fill: #FFFFFF
- bottom_line_2 fill: #5DDCFF
- top_quote fill: #FFF200
- stroke: #111111

5. purple_white_secret
Use for:
- hidden truth
- mystery
- disappearance
- secret identity
- shocking past
- suspicious SNS or message
Colors:
- bottom_line_1 fill: #FFFFFF
- bottom_line_2 fill: #B66CFF
- top_quote fill: #FF4FD8
- stroke: #111111

6. red_white_crisis
Use for:
- lawsuit
- police
- lawyer
- debt
- collapse
- compensation
- destruction
Colors:
- bottom_line_1 fill: #FFFFFF
- bottom_line_2 fill: #FF2A2A
- top_quote fill: #FFF200
- stroke: #111111

7. orange_yellow_comedy
Use for:
- 2ch comedy
- humiliation
- unemployed character
- ironic downfall
- misunderstanding
- absurd situation
Colors:
- bottom_line_1 fill: #FFF200
- bottom_line_2 fill: #FF8C00
- top_quote fill: #48FF4E
- stroke: #111111

Important:
- bottom_line_2 should usually get the strongest color.
- Stroke must be thick black or near-black.
- Do not invent a new theme unless absolutely necessary.
- If multiple themes fit, choose the one that best matches the strongest CTR hook.

━━━━━━━━━━━━━━━━━━━━
VISUAL PROMPT CREATION RULE
━━━━━━━━━━━━━━━━━━━━

You must create "visual_prompt" by combining:

1. The visual prompt constants provided by code
2. The story-specific visual concept from the title and summary
3. The detected niche and CTR angle
4. The selected visual style: ${visualStyle}

The visual prompt must include:
- visual style
- character roles
- character appearance
- character emotions
- character actions
- setting
- main evidence object if relevant
- composition
- lighting
- emotional contrast
- bottom safe area rule
- strict no-text rule

For cinematic:
- Make it look like a realistic Japanese TV drama scene.
- Use live-action realism and emotional acting.

For anime:
- Make it look like a serious Japanese anime drama thumbnail.
- Use expressive anime faces and bold dramatic lighting.

For both:
- No text
- No Japanese characters
- No subtitles
- No speech bubbles
- No logos
- No watermark
- The final Japanese text will be added later by code
- Keep the bottom 28 percent darker, cleaner, and less detailed for large Japanese text overlay
- Keep important faces in the upper and middle areas
- Use split-screen when the story has two opposing characters
- Make the visual clearly match the selected thumbnail copy

━━━━━━━━━━━━━━━━━━━━
OUTPUT JSON SCHEMA
━━━━━━━━━━━━━━━━━━━━

Return valid JSON only.
Do not use markdown.
Do not add explanations outside JSON.

{
  "detected_niche": "string",
  "sub_niche": "string",
  "dominant_emotion": "string",
  "secondary_emotion": "string",
  "ctr_angle": "string",
  "core_conflict": "string",
  "thumbnail_copy": {
    "top_quote_enabled": true,
    "top_quote": "string",
    "bottom_line_1": "string",
    "bottom_line_2": "string"
  },
  "copy_role": {
    "top_quote": "shocking dialogue | empty",
    "bottom_line_1": "context setup",
    "bottom_line_2": "main punchline"
  },
  "text_color": {
    "theme": "cyan_white_revenge | yellow_red_betrayal | gold_white_success | blue_white_emotional | purple_white_secret | red_white_crisis | orange_yellow_comedy",
    "bottom_line_1": {
      "fill": "hex color",
      "stroke": "hex color"
    },
    "bottom_line_2": {
      "fill": "hex color",
      "stroke": "hex color"
    },
    "top_quote": {
      "fill": "hex color",
      "stroke": "hex color"
    },
    "reason": "string"
  },
  "visual_style": "${visualStyle}",
  "visual_spec": {
    "composition": "string",
    "main_characters": [
      {
        "role": "string",
        "appearance": "string",
        "emotion": "string",
        "action": "string",
        "position": "left | right | center | foreground | background"
      }
    ],
    "setting": "string",
    "must_include_visual_elements": ["string"],
    "must_avoid_visual_elements": ["text", "Japanese characters", "subtitles", "speech bubbles", "logos", "watermark"],
    "bottom_safe_area": "Keep the bottom 28 percent darker and less detailed for text overlay."
  },
  "visual_prompt": "string"
}
`;
