// Auto-generated by MaVid UI (edit settings)
// File path: contents/constants/index.js
// Hằng chỉnh trong Settings nằm trong appSettings.js (re-export bên dưới).

export { flowSettings, GEMINI_CONFIG, GEMINI_CHUNK_SIZE, STOCK_VIDEO, SUBTITLE, LOGO, VIDEO_STORAGE_ROOT } from './appSettings.js';

export const MAKE_VIDEO_MODE = {
  FROM_AUDIO: 'from_audio',
  REUP_FULL: 'reup_full',
};

export const VIDEO_TYPE = {
  '2CH': '2ch',
  STORY: 'story',
};

export const LANGUAGES_NEED_UPDATE_TRANSCRIPT = ['ja'];

export const META_DATA = {
  NICHE: 'Niche',
  TITLE: 'Title',
  DESCRIPTION: 'Description',
  TAGS: 'Tags',
};

export const DEFAULT_VIDEO = {
  BACKGROUND_VIDEO: 'cat',
};

export const AUDIO_SPEED = 0.91;
